apiVersion: apps/v1
kind: Deployment
metadata:
name: ad-service
namespace: jarchia
spec:
replicas: 2
selector:
matchLabels:
app: ad-service
template:
metadata:
labels:
app: ad-service
spec:
containers:
- name: ad-service
image: jarchia/ad-service:latest
ports:
- containerPort: 8083


