apiVersion: apps/v1
kind: Deployment
metadata:
name: eitaa-service
namespace: jarchia
spec:
replicas: 2
selector:
matchLabels:
app: eitaa-service
template:
metadata:
labels:
app: eitaa-service
spec:
containers:
- name: eitaa-service
image: jarchia/eitaa-service:latest
ports:
- containerPort: 8088


