apiVersion: apps/v1
kind: Deployment
metadata:
name: geo-service
namespace: jarchia
spec:
replicas: 2
selector:
matchLabels:
app: geo-service
template:
metadata:
labels:
app: geo-service
spec:
containers:
- name: geo-service
image: jarchia/geo-service:latest
ports:
- containerPort: 8084


